Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -31,7 +31,6 @@ jobs:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       AWS_DEFAULT_REGION: ${{ github.event.inputs.region }}
-      TF_LOG: DEBUG  # Enable verbose logging for Terraform
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -69,14 +68,7 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: |
-          terraform plan -out=tfplan -json
-          if [[ $? -ne 0 ]]; then
-            echo "Terraform plan failed."
-            exit 1
-          fi
-
-      - name: Generate tfplan.json
-        run: |
+          terraform plan -out=tfplan -json || { echo "Terraform plan failed"; exit 1; }
           for i in {1..3}; do
             terraform show -json tfplan > tfplan.json && break || sleep 5
           done
@@ -89,7 +81,6 @@ jobs:
         run: |
           if ! jq '.' tfplan.json; then
             echo "tfplan.json is not valid JSON. Check for errors in the Terraform plan."
-            cat tfplan.json || echo "Cannot display tfplan.json content."
             exit 1
           fi
 
@@ -166,7 +157,8 @@ jobs:
                          -upgrade
 
       - name: Terraform Plan (Destroy)
-        run: terraform plan -destroy -out=tfplan
+        run: |
+          terraform plan -destroy -out=tfplan
 
       - name: Terraform Apply (Destroy)
         run: |
