Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -80,7 +80,11 @@ jobs:
 
       - name: Debug Tags
         run: |
-          jq '.resource_changes[] | {type: .type, tags: .change.after.tags}' tfplan.json || echo "No tags found or invalid JSON."
+          if [ -f tfplan.json ]; then
+            jq '.resource_changes[]? | {type: .type, tags: .change.after.tags}' tfplan.json || echo "No tags found or invalid JSON."
+          else
+            echo "tfplan.json not found."
+          fi
 
       - name: OPA Policy Check
         id: opa_check
